apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-deployment
  namespace: smart-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
      - name: search-engine
        image: dansil2301/search_engine:latest
        ports:
        - containerPort: 8080
