apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-deployment
  namespace: smart-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
      - name: search-engine
        image: dansil2301/search_engine:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: 8080
        - name: DATABASE_DSN
          value: postgres://postgres:search_engine_pwd@search-engine-database-service:5432/search_engine_db?sslmode=disable
        - name: OPENAI_APIKEY
          value: hehe
        volumeMounts:
        - name: search-engine-storage
          mountPath: /app/.appdata
      volumes:
      - name: search-engine-storage
        persistentVolumeClaim:
          claimName: search-engine-pvc
