apiVersion: v1
kind: Service
metadata:
  name: search-engine-service
  namespace: smart-search
spec:
  selector:
    app: search-engine
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32001
  type: NodePort
