apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-engine-hpa
  namespace: smart-search
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-engine-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
