apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-engine-pvc
  namespace: smart-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard