apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: load-testing
spec:
  selector:
    app: locust
    role: master
  ports:
    - name: web
      port: 8089
      targetPort: 8089
    - name: master
      port: 5557
      targetPort: 5557
  type: LoadBalancer
