apiVersion: v1
clusters:
- cluster:
    certificate-authority: \\wsl.localhost\Ubuntu\home\danila\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Tue, 30 Sep 2025 22:35:15 CEST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:55669
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 10 Oct 2025 20:48:49 CEST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: \\wsl.localhost\Ubuntu\home\danila\.minikube\profiles\minikube\client.crt
    client-key: \\wsl.localhost\Ubuntu\home\danila\.minikube\profiles\minikube\client.key