apiVersion: v1
kind: Service
metadata:
  name: search-llm-service
  namespace: smart-search
spec:
  selector:
    app: search-llm
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32000
  type: NodePort
