apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: smart-search
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32020
