apiVersion: v1
kind: Service
metadata:
  name: search-gateway-service
  namespace: smart-search
spec:
  selector:
    app: search-gateway
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32002
  type: NodePort
