apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: smart-search
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090
  selector:
    app: kafdrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: smart-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:3.31.0
          env:
            - name: KAFKA_BROKERCONNECT
              value: "my-cluster-kafka-bootstrap:9092"
            - name: JVM_OPTS
              value: "-Xms128M -Xmx512M"
          ports:
            - containerPort: 9000
